oiip-data-viewer:
  image: podaac-ci.jpl.nasa.gov:5000/oiip/oiip-data-viewer:latest
  ports:
    - 8102:80
  volumes:
    - ./oiip-data-viewer:/usr/share/nginx/html/app:ro
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./.htpasswd:/etc/nginx/.htpasswd:ro
    - ./oiip-data-viewer-logs:/var/log/nginx:rw
  privileged: true
