// Main menu actions
export const SET_MAIN_MENU_TAB_INDEX = "SET_MAIN_MENU_TAB_INDEX";
export const SET_MAIN_MENU_OPEN = "SET_MAIN_MENU_OPEN";

// Chart Actions
export const SET_SELECTED_DATASETS = "SET_SELECTED_DATASETS";
export const SET_X_AXIS_VARIABLE = "SET_X_AXIS_VARIABLE";
export const SET_Y_AXIS_VARIABLE = "SET_Y_AXIS_VARIABLE";
export const SET_Z_AXIS_VARIABLE = "SET_Z_AXIS_VARIABLE";
export const INITIALIZE_CHART = "INITIALIZE_CHART";
export const SET_CHART_LOADING = "SET_CHART_LOADING";
export const UPDATE_CHART_DATA = "UPDATE_CHART_DATA";
export const SET_CHART_DISPLAY_OPTIONS = "SET_CHART_DISPLAY_OPTIONS";
export const CLOSE_CHART = "CLOSE_CHART";
export const SET_CHART_FORM_ERROR = "SET_CHART_FORM_ERROR";

// Layer Actions
export const SET_INSITU_LAYER_COLOR = "SET_INSITU_LAYER_COLOR";
export const ZOOM_TO_LAYER = "ZOOM_TO_LAYER";
export const SET_TRACK_SELECTED = "SET_TRACK_SELECTED";

// Search Actions
export const SET_SEARCH_DATE_RANGE = "SET_SEARCH_DATE_RANGE";
export const SET_SEARCH_SELECTED_AREA = "SET_SEARCH_SELECTED_AREA";
export const SET_SEARCH_LOADING = "SET_SEARCH_LOADING";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";

// Map Actions
export const ENABLE_AREA_SELECTION = "ENABLE_AREA_SELECTION";
export const DISABLE_AREA_SELECTION = "DISABLE_AREA_SELECTION";
export const REMOVE_ALL_AREA_SELECTIONS = "CLEAR_AREA_SELECTION";
export const REMOVE_GEOMETRY_FROM_MAP = "REMOVE_GEOMETRY_FROM_MAP";
